<a href="https://colab.research.google.com/github/Siddharth-Lokhande/data_science/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [4]:
arr=pd.Series([1,1,6,5,4],index=['a','b','c','d','e'])

In [5]:
arr

a    1
b    1
c    6
d    5
e    4
dtype: int64

In [8]:
arr=pd.read_csv("data/iris.csv")

In [10]:
arr

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

from matplotlib import pyplot as plt
arr['sepal.length'].plot(kind='hist', bins=20, title='sepal.length')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
arr['sepal.width'].plot(kind='hist', bins=20, title='sepal.width')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
arr['petal.length'].plot(kind='hist', bins=20, title='petal.length')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
arr['petal.width'].plot(kind='hist', bins=20, title='petal.width')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
arr.groupby('variety').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
arr.plot(kind='scatter', x='sepal.length', y='sepal.width', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
arr.plot(kind='scatter', x='sepal.width', y='petal.length', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
arr.plot(kind='scatter', x='petal.length', y='petal.width', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
arr['sepal.length'].plot(kind='line', figsize=(8, 4), title='sepal.length')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
arr['sepal.width'].plot(kind='line', figsize=(8, 4), title='sepal.width')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
arr['petal.length'].plot(kind='line', figsize=(8, 4), title='petal.length')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
arr['petal.width'].plot(kind='line', figsize=(8, 4), title='petal.width')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(arr['variety'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(arr, x='sepal.length', y='variety', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(arr['variety'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(arr, x='sepal.width', y='variety', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(arr['variety'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(arr, x='petal.length', y='variety', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(arr['variety'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(arr, x='petal.width', y='variety', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [12]:
arr.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [13]:
arr.tail()

     sepal.length  sepal.width  petal.length  petal.width    variety
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [19]:
arr.describe()

       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [21]:
arr.insert(0, 'id', range(len(arr)))

ValueError: cannot insert id, already exists

In [15]:
arr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

DATA SELECTION

In [22]:
arr["id"]

0        0
1        1
2        2
3        3
4        4
      ...
145    145
146    146
147    147
148    148
149    149
Name: id, Length: 150, dtype: int64

In [24]:
arr[["id","sepal.length"]]

      id  sepal.length
0      0           5.1
1      1           4.9
2      2           4.7
3      3           4.6
4      4           5.0
..   ...           ...
145  145           6.7
146  146           6.3
147  147           6.5
148  148           6.2
149  149           5.9

[150 rows x 2 columns]

In [27]:
arr.iloc[0]

id                   0
sepal.length       5.1
sepal.width        3.5
petal.length       1.4
petal.width        0.2
variety         Setosa
Name: 0, dtype: object

In [29]:
arr2=pd.read_csv("data/copy.csv")

In [31]:
arr2.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           NaN          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          NaN  Setosa
2           NaN          3.2           1.3          0.2  Setosa
3           4.6          3.1           NaN          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [33]:
arr2.dropna()

     sepal.length  sepal.width  petal.length  petal.width    variety
4             5.0          3.6           1.4          0.2     Setosa
6             4.6          3.4           1.4          0.3     Setosa
7             5.0          3.4           1.5          0.2     Setosa
8             4.4          2.9           1.4          0.2     Setosa
9             4.9          3.1           1.5          0.1     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[145 rows x 5 columns]

In [41]:
arr2.fillna(arr2.mean(), inplace=True)

TypeError: can only concatenate str (not "int") to str

In [36]:
arr2.rename

     sepal.length  sepal.width  petal.length  petal.width    variety
0             NaN          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          NaN     Setosa
2             NaN          3.2           1.3          0.2     Setosa
3             4.6          3.1           NaN          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [46]:
arr2['sepal.width']=arr2['sepal.width'].astype(str)

In [47]:
arr2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    object
 1   sepal.width   150 non-null    object
 2   petal.length  148 non-null    float64
 3   petal.width   149 non-null    float64
 4   variety       149 non-null    object
dtypes: float64(2), object(3)
memory usage: 6.0+ KB

In [49]:
arr2.to_csv("data/dified.csv")

In [51]:
df1=pd.DataFrame({"name":["Harry","rohan","parth","soham"],"marks":[11,99,52,78],})

In [52]:
df1

    name  marks
0  Harry     11
1  rohan     99
2  parth     52
3  soham     78

In [53]:
df2=pd.DataFrame({"name":["diya","khyati","arya","krisha"],"marks":[15,86,46,63],})

In [54]:
df2

     name  marks
0    diya     15
1  khyati     86
2    arya     46
3  krisha     63

In [55]:
pd.concat([df1,df2])

     name  marks
0   Harry     11
1   rohan     99
2   parth     52
3   soham     78
0    diya     15
1  khyati     86
2    arya     46
3  krisha     63

In [56]:
df1=pd.DataFrame({"name":["sakshi","sneha","shraddha"],"marks":[31,41,51],})

In [57]:
df1

       name  marks
0    sakshi     31
1     sneha     41
2  shraddha     51

merging 2 dataframe

In [58]:
df2=pd.DataFrame({"name":["sakshi","sneha","shraddha"],"rollno":[3551,4441,6651],})

In [59]:
pd.merge(df1,df2,on="name")

       name  marks  rollno
0    sakshi     31    3551
1     sneha     41    4441
2  shraddha     51    6651